name: cryosat-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fiona
  - fontconfig
  - freetype
  - future
  - gdal
  - geopandas
  - graphviz
  - h5py
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - shapely
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
    - ..
